// ============================================================
// DEVOTION DATA — STUDENT-FACING PRESENTATION — WEEKS 21–30
// FILE CHUNKING: split across data_wk{N}-{N+9}.js files (10 weeks/file), all
// merging into the same global window.DEVOTIONS. Load in ascending order in index.html.
// Structure: DEVOTIONS[term][week] = { lessonTitle, passage, bigIdea, days: [day1..day4] }
// Each day = { label, theme, blocks: [ {type, ...} ] }
//
// Block types (all shown ON SCREEN to students unless noted):
//  - 'story'    : narration text, big storybook-style, read aloud together
//  - 'image'    : a comic panel, full width, with an optional short caption
//  - 'question' : a discussion question for the class — shown big.
//                 optional `hint` field is for the TEACHER ONLY (hidden behind a toggle)
//  - 'verse'    : a memory verse, shown as a feature slide
//  - 'prayer'   : a closing prayer, said together
//  - 'activity' : a short instruction students themselves act on (stand up, choose a side, etc.)
//
// CURRICULUM NOTE: Weeks 1–20 were built from "Connect B1 Upper Primary" (Luke's
// Gospel). Week 21 begins a deliberate switch to "Connect B2 Upper Primary"
// (Exodus), starting at that book's Lesson 1. Weeks 11–20 remain an intentional
// gap to be filled in later.
// ============================================================

window.DEVOTIONS = window.DEVOTIONS || {};
window.DEVOTIONS["Term 1"] = Object.assign(window.DEVOTIONS["Term 1"] || {}, {
    "Week 21": {
      lessonTitle: "Survivor: Egypt Begins",
      passage: "Exodus 1:1—2:10",
      bigIdea: "God keeps his promises, even when things look hopeless.",
      source: "Connect B2 Upper Primary — Lesson 1",
      days: [
        // ---------------- DAY 1 (MON) ----------------
        {
          label: "Monday",
          theme: "A big family in Egypt",
          blocks: [
            { type: "story", text: "Welcome back! We're starting a brand new Bible story today, from a book called Exodus. It's about a man named Moses — but before we meet him, we need to go back and see how his people ended up in Egypt in the first place." },
            { type: "story", text: "Long ago, God promised a man named Abraham that his family would grow into a great nation, as many as the stars in the sky. Today's story shows that promise starting to come true — in a place nobody would have expected." },
            { type: "story", text: "Abraham's grandson Jacob had a son named Joseph, who became a powerful leader in Egypt. When hard times came, Jacob moved his whole family — eleven other sons and all their households, seventy people in total — down to Egypt to live near Joseph." },
            { type: "story", text: "Jacob's family settled in a region called Goshen — good land for grazing their sheep and goats. After so many years apart, and after everything Joseph's brothers had once done to him, the family was finally reunited, safe, and fed, all because of the position God had put Joseph in." },
            { type: "question", text: "Why do you think Jacob's family needed to move all the way to Egypt?", hint: "Guide toward: there was a severe famine in their own land, and Joseph — through God's plan — was in a position in Egypt to save his family from starving." },
            { type: "story", text: "Years passed. Jacob, Joseph, and all of that generation eventually died. But their families kept having children, and grandchildren, and great-grandchildren — until the whole region of Goshen, where they lived, was full of them." },
            { type: "story", text: "Jacob's twelve sons — Reuben, Simeon, Levi, Judah, and the rest — each became the father of a whole tribe. That's where the twelve tribes of Israel come from: an entire nation, all descended from one family that started with just seventy people in Goshen." },
            { type: "question", text: "Remember God's promise to Abraham, that his family would become a great nation, too many to count? What do you notice happening to that family here, generations later, in Egypt?", hint: "Guide toward: God's promise was quietly coming true, even in a foreign country, far from home — the Israelites were multiplying exactly as God had said they would." },
            { type: "activity", text: "Retelling relay: with a partner, take turns retelling today's story in just three sentences each — one about God's promise to Abraham, one about Jacob's move to Egypt, and one about how the family grew into twelve tribes. See how much detail you can pack in!" },
            { type: "verse", reference: "Deuteronomy 4:39 (CEV)", text: "\u201cRemember that the Lord is the only true God, whether in the sky above or on the earth below.\u201d" },
            { type: "activity", text: "Let's read this week's memory verse together two or three times, then try saying it once without looking!" },
            { type: "prayer", text: "Dear God, thank you that you are always faithful to your promises, even when we can't see it happening. Thank you for growing Abraham's family, just like you said you would. Help us trust that you keep your word. Amen." },
          ],
          lessonPlan: {
            duration: "10\u201315 minutes",
            passage: "Exodus 1:1\u20137",
            topic: "A big family in Egypt",
            bigIdea: "God keeps his promises, even when things look hopeless.",
            learningIntentions: [
              "We are learning how Abraham's family came to live in Egypt.",
              "We are learning that God's promise to Abraham — that his family would become a great nation — was coming true, generation by generation.",
              "I can explain why Jacob's family moved to Egypt.",
            ],
            assessment: "Check that students can retell, in their own words, how Jacob's family ended up in Egypt and can connect their growth in numbers to God's promise to Abraham.",
            resources: [
              "Screen/device to display the week's content (already embedded in the app)",
            ],
            script: [
              {
                heading: "Introducing a new story",
                minutes: "2\u20133 min",
                teacherTalk: "\u201cWe're starting a brand new Bible story today, from a book called Exodus, about a man named Moses. But first we need to see how his people ended up in Egypt.\u201d Briefly remind students of God's promise to Abraham (a great nation, descendants like the stars) if they covered this in earlier terms \u2014 otherwise just introduce it fresh.",
                activityNote: null,
                keyQuestion: null,
                teacherGuidance: null,
              },
              {
                heading: "Jacob's family moves to Egypt",
                minutes: "3\u20134 min",
                teacherTalk: "Tell the story of Jacob moving his family of seventy \u2014 eleven sons and their households \u2014 to Egypt to be near Joseph, who had become a powerful leader there. Mention that they settled in Goshen, good land for their flocks, and that the family was finally reunited after everything that had happened between Joseph and his brothers.",
                activityNote: null,
                keyQuestion: "Why do you think Jacob's family needed to move all the way to Egypt?",
                teacherGuidance: "Guide toward: there was a severe famine in their own land, and Joseph \u2014 through God's plan \u2014 was in a position in Egypt to save his family from starving.",
              },
              {
                heading: "A family that keeps growing",
                minutes: "3\u20134 min",
                teacherTalk: "\u201cYears passed. Jacob, Joseph, and all of that generation eventually died. But their families kept having children, and grandchildren, and great-grandchildren \u2014 until the whole region of Goshen was full of them.\u201d Explain that Jacob's twelve sons each became the father of a whole tribe \u2014 that's where the twelve tribes of Israel come from.",
                activityNote: null,
                keyQuestion: "Remember God's promise to Abraham, that his family would become a great nation? What do you notice happening to that family here, generations later, in Egypt?",
                teacherGuidance: "Guide toward: God's promise was quietly coming true, even in a foreign country, far from home \u2014 the Israelites were multiplying exactly as God had said they would.",
              },
              {
                heading: "Retelling relay",
                minutes: "2\u20133 min",
                teacherTalk: "Pair students up and have them retell today's story in three sentences each \u2014 God's promise to Abraham, Jacob's move to Egypt, and the growth into twelve tribes.",
                activityNote: "Use the built-in retelling relay activity block.",
                keyQuestion: null,
                teacherGuidance: null,
              },
              {
                heading: "Memory verse",
                minutes: "2\u20133 min",
                teacherTalk: "Introduce this unit's memory verse, Deuteronomy 4:39 (CEV). Read it together two or three times, then try it once without looking.",
                activityNote: "Use the built-in verse block, then the say-it-together activity that follows it in the app.",
                keyQuestion: null,
                teacherGuidance: null,
              },
            ],
            whereToNext: "Day 2 introduces a new king of Egypt who turns on the Israelites and forces them into slavery \u2014 even though it doesn't stop their numbers from growing.",
          },
        },
        // ---------------- DAY 2 (TUE) ----------------
        {
          label: "Tuesday",
          theme: "A king who forgot",
          blocks: [
            { type: "story", text: "Last time, we saw Jacob's family grow into a huge nation while living in Egypt \u2014 just like God had promised Abraham it would. But years later, everything changed." },
            { type: "story", text: "A new king came to power in Egypt. He had never known Joseph, and he didn't care what Joseph had once done for the country. When he looked at the Israelites, all he saw was a huge crowd of foreigners \u2014 and he got scared." },
            { type: "question", text: "Why do you think this new king felt threatened by how big the Israelite family had grown?", hint: "Guide toward: he worried they were too powerful, that they might join Egypt's enemies in a war, or even take over. It's worth noticing the irony \u2014 the very growth that showed God keeping his promise is exactly what frightened the king." },
            { type: "image", key: "wk21-01-slave-labour", caption: "So the king made the Israelites into slaves, forcing them into hard labour building his cities." },
            { type: "story", text: "The Israelites were forced to build entire cities for the king — Pithom and Rameses — hauling bricks and stone under harsh taskmasters, day after day, with no mercy shown to them at all." },
            { type: "activity", text: "Everyone stand up. Mime stacking heavy bricks as fast as you can for five seconds... now stop and sit back down. Imagine doing that all day long, every single day, for years — that's what the Israelites endured." },
            { type: "story", text: "But here's the surprising part: the harder the Egyptians worked the Israelites, the more the Israelite families kept growing! Nothing the king did could stop it." },
            { type: "question", text: "The Israelites were suffering as slaves, yet they kept growing in number. What does that tell us about God's promises, even during hard and unfair times?", hint: "Guide toward: God's promise didn't stop just because life got hard \u2014 he was still faithfully keeping his word to Abraham, even in the middle of real suffering." },
            { type: "question", text: "The harder the king tried to crush the Israelites, the more God's promise kept coming true anyway. Why do you think the king couldn't stop something God had promised?", hint: "Guide toward: no earthly king, no matter how powerful, can overpower God's plans. This sets up the whole rest of the Exodus story — a human king going head-to-head with God, and losing." },
            { type: "verse", reference: "Deuteronomy 4:39 (CEV)", text: "\u201cRemember that the Lord is the only true God, whether in the sky above or on the earth below.\u201d" },
            { type: "prayer", text: "Dear God, thank you that you don't stop keeping your promises, even when life feels hard or unfair. Help us to trust you when things around us don't make sense. Amen." },
          ],
          lessonPlan: {
            duration: "10\u201315 minutes",
            passage: "Exodus 1:8\u201314",
            topic: "A king who forgot",
            bigIdea: "God keeps his promises, even when things look hopeless.",
            learningIntentions: [
              "We are learning that a new king in Egypt turned against the Israelites out of fear.",
              "We are learning that the Israelites were forced into hard slave labour, but kept growing in number anyway.",
              "I can explain why the growth of Abraham's family both showed God's promise and provoked the king's fear.",
            ],
            assessment: "Listen for whether students can articulate why the king felt threatened, and whether they can connect the Israelites' continued growth under oppression back to God's faithfulness.",
            resources: [
              "Screen/device to display the comic panel and week's content (already embedded in the app)",
            ],
            script: [
              {
                heading: "Recap and a new king",
                minutes: "2\u20133 min",
                teacherTalk: "\u201cLast time, we saw Jacob's family grow into a huge nation while living in Egypt. But years later, everything changed.\u201d Introduce the new king who never knew Joseph and feared the Israelites.",
                activityNote: null,
                keyQuestion: "Why do you think this new king felt threatened by how big the Israelite family had grown?",
                teacherGuidance: "Guide toward: he worried they were too powerful, that they might join Egypt's enemies in a war, or even take over. Notice the irony \u2014 the very growth that showed God's promise is what frightened the king.",
              },
              {
                heading: "Forced into slavery",
                minutes: "3\u20134 min",
                teacherTalk: "Show the comic panel and explain that the king made the Israelites into slaves, forcing them into hard labour building his cities, Pithom and Rameses, under harsh taskmasters.",
                activityNote: "Show comic panel wk21-01-slave-labour.",
                keyQuestion: null,
                teacherGuidance: null,
              },
              {
                heading: "Feel the labour",
                minutes: "1\u20132 min",
                teacherTalk: "Have the whole class stand and mime stacking heavy bricks as fast as they can for five seconds, then sit. Point out that the Israelites did that all day, every day, for years.",
                activityNote: "Use the built-in brick-miming activity block.",
                keyQuestion: null,
                teacherGuidance: null,
              },
              {
                heading: "Growing anyway",
                minutes: "3\u20134 min",
                teacherTalk: "\u201cThe harder the Egyptians worked the Israelites, the more the Israelite families kept growing! Nothing the king did could stop it.\u201d",
                activityNote: null,
                keyQuestion: "The Israelites were suffering as slaves, yet they kept growing in number. What does that tell us about God's promises, even during hard and unfair times?",
                teacherGuidance: "Guide toward: God's promise didn't stop just because life got hard \u2014 he was still faithfully keeping his word to Abraham, even in the middle of real suffering.",
              },
              {
                heading: "A king versus God",
                minutes: "2\u20133 min",
                teacherTalk: "Open the second question about why the king couldn't stop what God had promised.",
                activityNote: null,
                keyQuestion: "The harder the king tried to crush the Israelites, the more God's promise kept coming true anyway. Why do you think the king couldn't stop something God had promised?",
                teacherGuidance: "Guide toward: no earthly king, no matter how powerful, can overpower God's plans. This sets up the whole rest of the Exodus story \u2014 a human king going head-to-head with God, and losing.",
              },
              {
                heading: "Memory verse",
                minutes: "2 min",
                teacherTalk: "Repeat this unit's memory verse, Deuteronomy 4:39 (CEV), together as a class.",
                activityNote: "Use the built-in verse block.",
                keyQuestion: null,
                teacherGuidance: null,
              },
            ],
            whereToNext: "Day 3 shows the king's cruelty getting worse still, and a mother's brave plan to save her baby son.",
          },
        },
        // ---------------- DAY 3 (WED) ----------------
        {
          label: "Wednesday",
          theme: "A basket of hope",
          blocks: [
            { type: "story", text: "Last time, we saw the king of Egypt force the Israelites into hard slave labour \u2014 but they kept growing in number anyway. The king tried something sneakier next: he told two Hebrew midwives, named Shiphrah and Puah, to secretly kill any baby boy they helped deliver." },
            { type: "story", text: "But Shiphrah and Puah feared God more than they feared Pharaoh. They refused to obey his order, and let the baby boys live \u2014 even though disobeying the most powerful man in Egypt was incredibly dangerous for them." },
            { type: "question", text: "Why do you think the midwives were willing to disobey Pharaoh's direct order, even though it put them at risk?", hint: "Guide toward: their respect and fear of God went deeper than their fear of Pharaoh \u2014 they trusted that obeying God, even at personal cost, mattered more than obeying an unjust human command." },
            { type: "story", text: "So the king came up with an even crueller plan: he ordered that every baby boy born to the Israelites should be thrown into the Nile River." },
            { type: "question", text: "How do you think Israelite parents felt when they heard this terrible order?", hint: "Accept any answer that captures fear, grief, or desperation \u2014 it must have felt like their hope for the future was under attack." },
            { type: "story", text: "During this time, a mother from the tribe of Levi had a baby boy. She hid him at home for three months. When she couldn't hide him safely any longer, she made a basket out of reeds, covered it with tar so it wouldn't leak, and placed it among the reeds at the edge of the Nile River. The baby's older sister stood nearby, watching to see what would happen to him." },
            { type: "image", key: "wk21-02-basket-in-reeds", caption: "The baby's mother placed him in a basket among the reeds, and his sister watched from a distance." },
            { type: "question", text: "This mother trusted God with her baby's life in an incredibly scary situation. What do you think gave her the courage to do this?", hint: "Guide toward: faith that the same God who had kept his promise to Abraham could be trusted with her son's life too, even when she couldn't control what happened next." },
            { type: "activity", text: "Turn to a partner and name two acts of courage from today's story \u2014 one from the midwives, and one from the baby's mother. Talk together about which one you think would have been harder to do." },
            { type: "verse", reference: "Deuteronomy 4:39 (CEV)", text: "\u201cRemember that the Lord is the only true God, whether in the sky above or on the earth below.\u201d" },
            { type: "prayer", text: "Dear God, please give us courage to trust you in scary situations, like the midwives and this mother did. Help us remember that you are watching over us even when we feel afraid. Amen." },
          ],
          lessonPlan: {
            duration: "10\u201315 minutes",
            passage: "Exodus 1:15\u201322; 2:1\u20134",
            topic: "A basket of hope",
            bigIdea: "God keeps his promises, even when things look hopeless.",
            learningIntentions: [
              "We are learning about Pharaoh's order to kill Israelite baby boys.",
              "We are learning how one mother bravely protected her son by placing him in a basket on the Nile.",
              "I can describe the courage and trust this mother showed in a frightening situation.",
            ],
            assessment: "Check that students can retell the basket scene accurately and can articulate what trust in God might have looked like for this mother.",
            resources: [
              "Screen/device to display the comic panel and week's content (already embedded in the app)",
            ],
            script: [
              {
                heading: "Shiphrah and Puah's courage",
                minutes: "3\u20134 min",
                teacherTalk: "Introduce Pharaoh's first, sneakier plan: telling the Hebrew midwives Shiphrah and Puah to secretly kill baby boys at birth. They feared God more than Pharaoh, and refused.",
                activityNote: null,
                keyQuestion: "Why do you think the midwives were willing to disobey Pharaoh's direct order, even though it put them at risk?",
                teacherGuidance: "Guide toward: their respect and fear of God went deeper than their fear of Pharaoh \u2014 they trusted that obeying God, even at personal cost, mattered more than obeying an unjust human command.",
              },
              {
                heading: "The king's cruel order",
                minutes: "2\u20133 min",
                teacherTalk: "\u201cSo the king came up with an even crueller plan: he ordered that every baby boy born to the Israelites should be thrown into the Nile River.\u201d",
                activityNote: null,
                keyQuestion: "How do you think Israelite parents felt when they heard this terrible order?",
                teacherGuidance: "Accept any answer that captures fear, grief, or desperation \u2014 it must have felt like their hope for the future was under attack.",
              },
              {
                heading: "A mother's brave plan",
                minutes: "3\u20134 min",
                teacherTalk: "Tell the story of the Levite mother hiding her son for three months, then placing him in a tar-covered basket among the reeds of the Nile, with his sister watching nearby. Show the comic panel.",
                activityNote: "Show comic panel wk21-02-basket-in-reeds.",
                keyQuestion: null,
                teacherGuidance: null,
              },
              {
                heading: "Where did her courage come from?",
                minutes: "2\u20133 min",
                teacherTalk: "Pause on the enormity of what this mother did before opening the question to the class.",
                activityNote: null,
                keyQuestion: "This mother trusted God with her baby's life in an incredibly scary situation. What do you think gave her the courage to do this?",
                teacherGuidance: "Guide toward: faith that the same God who had kept his promise to Abraham could be trusted with her son's life too, even when she couldn't control what happened next.",
              },
              {
                heading: "Naming the courage",
                minutes: "1\u20132 min",
                teacherTalk: "Have partners name and compare the two acts of courage from today's story: the midwives and the mother.",
                activityNote: "Use the built-in partner-discussion activity block.",
                keyQuestion: null,
                teacherGuidance: null,
              },
              {
                heading: "Memory verse",
                minutes: "2 min",
                teacherTalk: "Repeat this unit's memory verse, Deuteronomy 4:39 (CEV), together as a class.",
                activityNote: "Use the built-in verse block.",
                keyQuestion: null,
                teacherGuidance: null,
              },
            ],
            whereToNext: "Day 4 reveals who finds the basket \u2014 and how this baby's rescue connects all the way back to God's promise to Abraham.",
          },
        },
        // ---------------- DAY 4 (THU) ----------------
        {
          label: "Thursday",
          theme: "Pulled out of the water",
          blocks: [
            { type: "story", text: "Last time, a Levite mother placed her baby son in a basket among the reeds of the Nile River, with his sister watching from a distance to see what would happen to him." },
            { type: "story", text: "Soon, one of Pharaoh's own daughters came down to the riverbank to bathe. Walking along the water's edge with her attendants, she spotted the strange little basket tucked among the reeds and sent a servant to fetch it for her." },
            { type: "story", text: "When she opened the basket, she found the crying baby inside \u2014 and she felt sorry for him. She knew right away he must be one of the Hebrew babies, the very babies her own father had ordered to be thrown into this same river." },
            { type: "story", text: "Just then, the baby's sister came up and bravely asked the princess, \u2018Do you want me to find a Hebrew woman to nurse the baby for you?\u2019 The princess agreed \u2014 and, without realising it, the girl went and brought back the baby's own mother to care for him!" },
            { type: "question", text: "Isn't that amazing? Out of everyone in Egypt, this baby's own mother ended up being the one who got to raise him \u2014 with Pharaoh's daughter's protection. What do you think this shows us about God?", hint: "Guide toward: God was working behind the scenes the whole time, even in what looked like pure chance, to protect and provide for this baby." },
            { type: "story", text: "When the boy was old enough, his mother brought him to Pharaoh's daughter, who adopted him as her own son. She named him Moses, because she said, \u2018I pulled him out of the water.\u2019" },
            { type: "question", text: "Years earlier, God had told Abraham that his family would live as slaves in a foreign land \u2014 but that God would rescue them and keep his promise. How does baby Moses's rescue connect to that promise?", hint: "Guide toward: this baby, saved in such an unlikely way and raised right inside Pharaoh's own palace, was being prepared by God to one day become exactly the person he would use to rescue his people and keep his promise to Abraham." },
            { type: "activity", text: "Whole-week recap relay: in table groups, retell the whole week's story in order, one sentence each \u2014 the family growing in Egypt, the cruel king and slavery, the basket in the reeds, and finally baby Moses being rescued and named. See if your group can get through it without missing a part!" },
            { type: "verse", reference: "Deuteronomy 4:39 (CEV)", text: "\u201cRemember that the Lord is the only true God, whether in the sky above or on the earth below.\u201d" },
            { type: "activity", text: "Let's say this week's memory verse together one more time \u2014 see if we can do it from memory!" },
            { type: "prayer", text: "Dear God, thank you that you had a plan all along for Moses, even when things looked hopeless. Thank you that you have a plan for us too. Help us trust you, even when we can't see how things will work out. Amen." },
          ],
          lessonPlan: {
            duration: "10\u201315 minutes",
            passage: "Exodus 2:5\u201310",
            topic: "Pulled out of the water",
            bigIdea: "God keeps his promises, even when things look hopeless.",
            learningIntentions: [
              "We are learning how Pharaoh's daughter found and adopted baby Moses.",
              "We are learning that God was working behind the scenes to protect Moses and provide for him through his own mother.",
              "I can connect Moses's rescue back to God's promise to Abraham about rescuing his people.",
            ],
            assessment: "Check that students can retell how Moses was found and named, and can explain in their own words how his rescue connects to God's bigger promise to Abraham.",
            resources: [
              "Screen/device to display the week's content (already embedded in the app)",
            ],
            script: [
              {
                heading: "The princess finds the basket",
                minutes: "3\u20134 min",
                teacherTalk: "\u201cOne of Pharaoh's own daughters came down to bathe in the river, noticed the basket, and found the crying baby inside. She felt sorry for him and knew he must be one of the Hebrew babies.\u201d",
                activityNote: null,
                keyQuestion: null,
                teacherGuidance: null,
              },
              {
                heading: "A surprising turn",
                minutes: "3\u20134 min",
                teacherTalk: "\u201cThe baby's sister bravely asked the princess if she wanted a Hebrew woman to nurse the baby \u2014 and without realising it, brought back the baby's own mother!\u201d",
                activityNote: null,
                keyQuestion: "Out of everyone in Egypt, this baby's own mother ended up being the one who got to raise him. What do you think this shows us about God?",
                teacherGuidance: "Guide toward: God was working behind the scenes the whole time, even in what looked like pure chance, to protect and provide for this baby.",
              },
              {
                heading: "Moses is named",
                minutes: "2\u20133 min",
                teacherTalk: "\u201cWhen the boy was old enough, his mother brought him to Pharaoh's daughter, who adopted him as her own son and named him Moses, because she said, \u2018I pulled him out of the water.\u2019\u201d",
                activityNote: null,
                keyQuestion: null,
                teacherGuidance: null,
              },
              {
                heading: "Connecting back to the promise",
                minutes: "3\u20134 min",
                teacherTalk: "Remind students of God's promise to Abraham that his family would be rescued from slavery in a foreign land, then open the closing question.",
                activityNote: null,
                keyQuestion: "How does baby Moses's rescue connect to God's promise to Abraham?",
                teacherGuidance: "Guide toward: this baby, saved in such an unlikely way and raised right inside Pharaoh's own palace, was being prepared by God to one day become exactly the person he would use to rescue his people and keep his promise to Abraham.",
              },
              {
                heading: "Whole-week recap relay",
                minutes: "2\u20133 min",
                teacherTalk: "In table groups, have students retell the whole week's story in order, one sentence each: the family growing in Egypt, the cruel king and slavery, the basket in the reeds, and Moses's rescue and naming.",
                activityNote: "Use the built-in whole-week recap relay activity block.",
                keyQuestion: null,
                teacherGuidance: null,
              },
              {
                heading: "Memory verse, from memory",
                minutes: "2 min",
                teacherTalk: "Close the week by inviting the class to say the memory verse together entirely from memory, without looking at the screen.",
                activityNote: "Use the built-in verse block, then the say-it-together activity that follows it in the app.",
                keyQuestion: null,
                teacherGuidance: null,
              },
            ],
            whereToNext: "Week 22 (Lesson 2) picks up with Moses as a grown man, his flight from Egypt, and God calling him at the burning bush.",
          },
        },
      ],
    },
    "Week 22": {
      lessonTitle: "The Leader",
      passage: "Exodus 3:1—4:17",
      bigIdea: "God chooses ordinary, reluctant people and equips them for his extraordinary plans.",
      source: "Connect B2 Upper Primary — Lesson 2",
      days: [
        // ---------------- DAY 1 (MON) ----------------
        {
          label: "Monday",
          theme: "A blazing bush",
          blocks: [
            { type: "story", text: "Last time, baby Moses was rescued from the Nile and raised in Pharaoh's own palace. Today's story jumps ahead many years, to when Moses had grown into a man." },
            { type: "story", text: "One day, Moses saw an Egyptian mistreating one of his own Israelite people, and in anger, Moses killed the Egyptian. Afraid of what Pharaoh would do, Moses fled far away to a land called Midian, where he became a shepherd, married a woman named Zipporah, and quietly looked after his father-in-law's flock for years." },
            { type: "story", text: "Think about that change: Moses had grown up with every comfort in Pharaoh's own palace. Now, decades later, he was just an ordinary shepherd in the middle of nowhere, herding sheep for his father-in-law. It must have felt like his exciting future was long behind him." },
            { type: "story", text: "One ordinary day, while Moses was out with the sheep near a mountain called Horeb, he noticed something strange: a bush was on fire, blazing away — but it never burned up. Curious, Moses decided to go over and take a closer look." },
            { type: "question", text: "Why do you think Moses stopped to look closer at the bush, instead of just walking past it?", hint: "Accept any answer that notices Moses's curiosity at something so unusual — a fire that didn't destroy what it was burning. This small choice to pay attention is what led him to encounter God." },
            { type: "story", text: "As Moses got closer, God called out to him from the bush: \u201cMoses, Moses!\u201d Then God said, \u201cDo not come any closer. Take off your sandals, because the place where you are standing is holy ground.\u201d God then said, \u201cI am the God of your father — the God of Abraham, Isaac, and Jacob.\u201d At this, Moses hid his face, because he was afraid to look directly at God." },
            { type: "activity", text: "Everyone, mime slipping off your shoes right now, just like Moses did. Then turn to a partner: why do you think taking off your shoes was such an important way to show respect for where Moses was standing?" },
            { type: "question", text: "What does God's instruction \u2014 to take off his sandals because the ground was holy \u2014 tell us about who God is?", hint: "Guide toward: God is holy and set apart from everything else, worthy of reverence and respect. The ordinary ground became special simply because God was present there." },
            { type: "verse", reference: "Deuteronomy 4:39 (CEV)", text: "\u201cRemember that the Lord is the only true God, whether in the sky above or on the earth below.\u201d" },
            { type: "activity", text: "Let's read this week's memory verse together two or three times, then try saying it once without looking!" },
            { type: "prayer", text: "Dear God, thank you that you are holy, and that you still choose to speak to ordinary people like Moses \u2014 and like us. Help us to notice when you are trying to get our attention. Amen." },
          ],
          lessonPlan: {
            duration: "10\u201315 minutes",
            passage: "Exodus 3:1\u20136",
            topic: "A blazing bush",
            bigIdea: "God chooses ordinary, reluctant people and equips them for his extraordinary plans.",
            learningIntentions: [
              "We are learning how Moses ended up as a shepherd in Midian, far from Egypt.",
              "We are learning how God called out to Moses from a bush that burned but was never consumed.",
              "I can explain what God's instruction about holy ground tells us about who God is.",
            ],
            assessment: "Check that students can retell how Moses came to be in Midian and can describe what happened at the burning bush, including why God told him to remove his sandals.",
            resources: [
              "Screen/device to display the week's content (already embedded in the app)",
            ],
            script: [
              {
                heading: "From the palace to the desert",
                minutes: "3\u20134 min",
                teacherTalk: "\u201cLast time, baby Moses was rescued from the Nile and raised in Pharaoh's palace. Today we jump ahead many years.\u201d Explain that Moses killed an Egyptian who was mistreating an Israelite, then fled to Midian out of fear, where he became a shepherd and started a family. Pause on the huge change from palace prince to ordinary shepherd.",
                activityNote: null,
                keyQuestion: null,
                teacherGuidance: null,
              },
              {
                heading: "A strange sight",
                minutes: "2\u20133 min",
                teacherTalk: "\u201cOne ordinary day, while Moses was out with the sheep near Mount Horeb, he noticed a bush blazing with fire \u2014 but it never burned up.\u201d",
                activityNote: null,
                keyQuestion: "Why do you think Moses stopped to look closer at the bush, instead of just walking past it?",
                teacherGuidance: "Accept any answer that notices Moses's curiosity at something so unusual. This small choice to pay attention is what led him to encounter God.",
              },
              {
                heading: "Holy ground",
                minutes: "3\u20134 min",
                teacherTalk: "\u201cAs Moses got closer, God called out to him from the bush and told him to take off his sandals, because the ground he stood on was holy.\u201d Mention that God identified himself as the God of Abraham, Isaac, and Jacob, and that Moses hid his face, afraid to look at God directly.",
                activityNote: null,
                keyQuestion: null,
                teacherGuidance: null,
              },
              {
                heading: "Taking off our shoes",
                minutes: "1\u20132 min",
                teacherTalk: "Have the class mime removing their shoes like Moses, then discuss with a partner why that gesture mattered.",
                activityNote: "Use the built-in shoes-off activity block.",
                keyQuestion: null,
                teacherGuidance: null,
              },
              {
                heading: "What holy ground tells us",
                minutes: "2\u20133 min",
                teacherTalk: "Open the question about what this moment tells us about God's character.",
                activityNote: null,
                keyQuestion: "What does God's instruction about holy ground tell us about who God is?",
                teacherGuidance: "Guide toward: God is holy and set apart from everything else, worthy of reverence and respect. The ordinary ground became special simply because God was present there.",
              },
              {
                heading: "Memory verse",
                minutes: "2\u20133 min",
                teacherTalk: "Introduce this unit's memory verse, Deuteronomy 4:39 (CEV) \u2014 the same verse used across this unit. Read it together two or three times, then try it once without looking.",
                activityNote: "Use the built-in verse block, then the say-it-together activity that follows it in the app.",
                keyQuestion: null,
                teacherGuidance: null,
              },
            ],
            whereToNext: "Day 2 hears God's rescue plan for Israel and the mission he gives Moses.",
          },
        },
        // ---------------- DAY 2 (TUE) ----------------
        {
          label: "Tuesday",
          theme: "God's rescue plan",
          blocks: [
            { type: "story", text: "Last time, God spoke to Moses out of a bush that burned without being burned up, and told him he was standing on holy ground. God wasn't finished talking \u2014 he had a plan to share." },
            { type: "story", text: "God told Moses, \u201cI have seen how my people are suffering as slaves in Egypt. I have heard their cries, and I have come down to rescue them and bring them into a good land, a land flowing with milk and honey.\u201d Then God said something that must have made Moses's heart race: \u201cSo now, go. I am sending you to Pharaoh, to bring my people out of Egypt.\u201d" },
            { type: "question", text: "How do you think Moses felt in that moment, when God told him rescuing his whole people was going to be his job?", hint: "Guide toward: Moses likely felt shocked, unqualified, and afraid \u2014 he was a shepherd hiding out in the desert, not a powerful leader, and Pharaoh was the most powerful man in Egypt." },
            { type: "story", text: "Moses's very first response was, \u201cWho am I, that I should go to Pharaoh and bring the Israelites out of Egypt?\u201d It's the first of many excuses Moses is about to make this week! God's answer was simple: \u201cI will be with you.\u201d The mission was never going to depend on how qualified Moses felt \u2014 it depended on God being with him." },
            { type: "activity", text: "Turn to a partner: if God asked you to do something that felt way too big for you \u2014 like it did for Moses \u2014 what's the first thing you think you'd say back? Share one word or phrase with your partner." },
            { type: "story", text: "Moses asked God, \u201cWhen I go to the Israelites and say their God sent me, and they ask me his name, what should I tell them?\u201d God replied, \u201cI AM WHO I AM. Tell them: I AM has sent me to you.\u201d God explained he was the same God who had made promises to Abraham, Isaac, and Jacob." },
            { type: "question", text: "What do you think it means that God calls himself \u2018I AM'?", hint: "Guide toward: God has always existed and never changes \u2014 he is the same faithful God who made promises long ago to Abraham, and he is still that same God now, showing up for his people exactly when they need him." },
            { type: "verse", reference: "Deuteronomy 4:39 (CEV)", text: "\u201cRemember that the Lord is the only true God, whether in the sky above or on the earth below.\u201d" },
            { type: "prayer", text: "Dear God, thank you that you see and hear when your people are suffering, and that you always keep your promises. Thank you that you are the same faithful \u2018I AM' today, and that you are with us even when we feel unqualified. Amen." },
          ],
          lessonPlan: {
            duration: "10\u201315 minutes",
            passage: "Exodus 3:7\u201315",
            topic: "God's rescue plan",
            bigIdea: "God chooses ordinary, reluctant people and equips them for his extraordinary plans.",
            learningIntentions: [
              "We are learning that God saw and heard the suffering of the Israelites in Egypt.",
              "We are learning that God sent Moses with a mission to bring his people out of Egypt.",
              "I can explain what God's name \u2018I AM' tells us about who he is.",
            ],
            assessment: "Check that students can explain God's rescue plan and mission for Moses, and can say in their own words what the name \u2018I AM' reveals about God's character.",
            resources: [
              "Screen/device to display the week's content (already embedded in the app)",
            ],
            script: [
              {
                heading: "God has seen and heard",
                minutes: "3\u20134 min",
                teacherTalk: "\u201cGod told Moses, \u2018I have seen how my people are suffering as slaves in Egypt. I have heard their cries, and I have come down to rescue them.'\u201d",
                activityNote: null,
                keyQuestion: null,
                teacherGuidance: null,
              },
              {
                heading: "The mission",
                minutes: "2\u20133 min",
                teacherTalk: "\u201cGod said, \u2018So now, go. I am sending you to Pharaoh, to bring my people out of Egypt.'\u201d",
                activityNote: null,
                keyQuestion: "How do you think Moses felt in that moment, when God told him rescuing his whole people was going to be his job?",
                teacherGuidance: "Guide toward: Moses likely felt shocked, unqualified, and afraid \u2014 he was a shepherd hiding out in the desert, not a powerful leader, and Pharaoh was the most powerful man in Egypt.",
              },
              {
                heading: "\u2018Who am I?'",
                minutes: "2\u20133 min",
                teacherTalk: "\u201cMoses's first response was, \u2018Who am I, that I should go to Pharaoh?' God's answer was simple: \u2018I will be with you.' The mission never depended on Moses feeling qualified.\u201d",
                activityNote: null,
                keyQuestion: null,
                teacherGuidance: null,
              },
              {
                heading: "Making it personal",
                minutes: "1\u20132 min",
                teacherTalk: "Have partners share what they'd say back if God asked them to do something that felt too big.",
                activityNote: "Use the built-in partner-sharing activity block.",
                keyQuestion: null,
                teacherGuidance: null,
              },
              {
                heading: "I AM WHO I AM",
                minutes: "3\u20134 min",
                teacherTalk: "\u201cMoses asked what he should say God's name was. God replied, \u2018I AM WHO I AM \u2014 tell them I AM has sent me to you,' explaining he was the same God who had promised Abraham, Isaac, and Jacob.\u201d",
                activityNote: null,
                keyQuestion: "What do you think it means that God calls himself \u2018I AM'?",
                teacherGuidance: "Guide toward: God has always existed and never changes \u2014 he is the same faithful God who made promises long ago, still showing up for his people exactly when they need him.",
              },
              {
                heading: "Memory verse",
                minutes: "2 min",
                teacherTalk: "Repeat this unit's memory verse, Deuteronomy 4:39 (CEV), together as a class.",
                activityNote: "Use the built-in verse block.",
                keyQuestion: null,
                teacherGuidance: null,
              },
            ],
            whereToNext: "Day 3 shows Moses making excuses \u2014 and the signs God gives him to prove he really was sent by God.",
          },
        },
        // ---------------- DAY 3 (WED) ----------------
        {
          label: "Wednesday",
          theme: "Moses makes excuses",
          blocks: [
            { type: "story", text: "Last time, God told Moses his rescue plan and gave him a mission: go to Pharaoh and bring God's people out of Egypt. God told Moses to first gather the elders of Israel, explain the plan, and then go together to ask Pharaoh's permission to worship God in the wilderness." },
            { type: "story", text: "But Moses started to worry. \u201cWhat if they don't believe me, or listen to me?\u201d he asked God. So God gave Moses some proof to convince people God had really sent him: Moses's shepherd's staff turned into a snake, and then back into a staff again." },
            { type: "activity", text: "Everyone, pretend you're holding a shepherd's staff. Now imagine it suddenly turns into a snake right at your feet \u2014 act out Moses's reaction! (The Bible says he ran away from it.) Now freeze, reach down bravely, and pick it back up like Moses did when God told him to." },
            { type: "story", text: "Next, God made Moses's hand suddenly become covered in a skin disease, then healed it again, right in front of him. And God gave a third sign too: if people still didn't believe, Moses could pour water from the Nile onto the ground, and it would turn to blood." },
            { type: "question", text: "Why do you think God gave Moses these miraculous signs to perform, instead of just telling him to go and trust that people would believe him?", hint: "Guide toward: the signs gave Moses \u2014 and later, the Israelites and Pharaoh \u2014 real evidence that God's power was truly behind him. Seeing helped people believe." },
            { type: "question", text: "Moses kept coming up with reasons why he couldn't do what God asked. Have you ever felt like Moses \u2014 like you weren't good enough or ready enough for something you were asked to do?", hint: "Accept personal responses. Connect it back to the big idea: God equips the people he calls: he doesn't wait for us to feel confident before he can use us." },
            { type: "verse", reference: "Deuteronomy 4:39 (CEV)", text: "\u201cRemember that the Lord is the only true God, whether in the sky above or on the earth below.\u201d" },
            { type: "prayer", text: "Dear God, thank you that you don't need us to feel brave or ready before you can use us. Help us to trust you, even when we feel unsure of ourselves. Amen." },
          ],
          lessonPlan: {
            duration: "10\u201315 minutes",
            passage: "Exodus 3:16\u20144:9",
            topic: "Moses makes excuses",
            bigIdea: "God chooses ordinary, reluctant people and equips them for his extraordinary plans.",
            learningIntentions: [
              "We are learning that Moses doubted whether the Israelites would believe or listen to him.",
              "We are learning about the miraculous signs God gave Moses as proof of his calling.",
              "I can connect Moses's self-doubt to times I've felt unsure about something I was asked to do.",
            ],
            assessment: "Check that students can describe at least one of the signs God gave Moses and can explain why God provided this kind of proof.",
            resources: [
              "Screen/device to display the week's content (already embedded in the app)",
            ],
            script: [
              {
                heading: "The plan so far",
                minutes: "2\u20133 min",
                teacherTalk: "Recap that God told Moses to gather the elders of Israel, explain the plan, and then go together to ask Pharaoh's permission to worship God in the wilderness.",
                activityNote: null,
                keyQuestion: null,
                teacherGuidance: null,
              },
              {
                heading: "Moses worries \u2014 and the first sign",
                minutes: "2\u20133 min",
                teacherTalk: "\u201cMoses worried, \u2018What if they don't believe me?' So God gave him a sign: his staff turning into a snake and back again.\u201d",
                activityNote: null,
                keyQuestion: null,
                teacherGuidance: null,
              },
              {
                heading: "Act it out",
                minutes: "1\u20132 min",
                teacherTalk: "Have the class mime holding a staff that suddenly becomes a snake, acting out Moses's fear, then bravely picking it back up.",
                activityNote: "Use the built-in staff-to-snake activity block.",
                keyQuestion: null,
                teacherGuidance: null,
              },
              {
                heading: "Two more signs",
                minutes: "2\u20133 min",
                teacherTalk: "\u201cGod made Moses's hand become diseased, then healed it. And a third sign: water from the Nile poured on the ground would turn to blood.\u201d",
                activityNote: null,
                keyQuestion: "Why do you think God gave Moses these miraculous signs, instead of just telling him to trust that people would believe him?",
                teacherGuidance: "Guide toward: the signs gave Moses \u2014 and later the Israelites and Pharaoh \u2014 real evidence that God's power was truly behind him. Seeing helped people believe.",
              },
              {
                heading: "Making it personal",
                minutes: "3\u20134 min",
                teacherTalk: "Invite students to reflect honestly on times they've felt unqualified or unready for something.",
                activityNote: null,
                keyQuestion: "Have you ever felt like Moses \u2014 like you weren't good enough or ready enough for something you were asked to do?",
                teacherGuidance: "Accept personal responses. Connect it back to the big idea: God equips the people he calls: he doesn't wait for us to feel confident before he can use us.",
              },
              {
                heading: "Memory verse",
                minutes: "2 min",
                teacherTalk: "Repeat this unit's memory verse, Deuteronomy 4:39 (CEV), together as a class.",
                activityNote: "Use the built-in verse block.",
                keyQuestion: null,
                teacherGuidance: null,
              },
            ],
            whereToNext: "Day 4 shows Moses's final excuse \u2014 and how God provides his brother Aaron to help him.",
          },
        },
        // ---------------- DAY 4 (THU) ----------------
        {
          label: "Thursday",
          theme: "Moses and his helper",
          blocks: [
            { type: "story", text: "Last time, God gave Moses miraculous signs to prove that God had really sent him. But Moses had one more excuse left." },
            { type: "story", text: "\u201cPardon me, Lord,\u201d Moses said, \u201cI have never been a good speaker. I am slow of speech and tongue.\u201d He begged God to send someone else instead of him." },
            { type: "story", text: "This time, God's anger burned against Moses \u2014 after everything God had shown him, Moses was still trying to wriggle out of the job! But even angry, God didn't give up on Moses or walk away from the plan." },
            { type: "story", text: "Instead, God had an answer ready. He reminded Moses that his brother Aaron was already on his way to meet him, and that Aaron could speak on Moses's behalf, while Moses told him what to say and performed the signs God had given him. Together, the two brothers would go to Pharaoh." },
            { type: "question", text: "What does it show us about God that he had already arranged for Aaron to help Moses \u2014 even before Moses asked for help, and even while God was frustrated with him?", hint: "Guide toward: God knows our weaknesses ahead of time and provides exactly what we need to obey him. His patience and his provision go together \u2014 he doesn't demand that we do everything completely alone, even when he's disappointed in our reluctance." },
            { type: "activity", text: "Whole-week recap relay: in table groups, retell this whole week's story in order, one sentence each \u2014 the burning bush and holy ground, God's rescue plan and the name \u2018I AM', Moses's doubts and the three signs, and finally God providing Aaron. See if your group can get all the way through!" },
            { type: "question", text: "Think back over this whole week's story. Moses started out hiding by a burning bush, full of excuses and doubts. By the end, was he ready to go? What changed?", hint: "Guide toward: Moses wasn't naturally brave or qualified, but God's patient reassurance, the signs, and Aaron's help gave him what he needed to obey \u2014 even while he was probably still nervous." },
            { type: "verse", reference: "Deuteronomy 4:39 (CEV)", text: "\u201cRemember that the Lord is the only true God, whether in the sky above or on the earth below.\u201d" },
            { type: "activity", text: "Let's say this week's memory verse together one more time \u2014 see if we can do it from memory!" },
            { type: "prayer", text: "Dear God, thank you that you knew exactly what Moses needed, even before he asked, and that you didn't give up on him even when he kept making excuses. Thank you that you know what we need too. Help us to trust you and obey, even when we feel unsure. Amen." },
          ],
          lessonPlan: {
            duration: "10\u201315 minutes",
            passage: "Exodus 4:10\u201317",
            topic: "Moses and his helper",
            bigIdea: "God chooses ordinary, reluctant people and equips them for his extraordinary plans.",
            learningIntentions: [
              "We are learning about Moses's final excuse \u2014 that he wasn't a good speaker.",
              "We are learning how God provided Aaron to help Moses speak to Pharaoh.",
              "I can explain what God providing Aaron shows us about how God equips the people he calls.",
            ],
            assessment: "Check that students can explain Moses's final objection and describe how God's provision of Aaron addressed it, and can summarise how Moses changed across the week.",
            resources: [
              "Screen/device to display the week's content (already embedded in the app)",
            ],
            script: [
              {
                heading: "One last excuse",
                minutes: "2\u20133 min",
                teacherTalk: "\u201cMoses said, \u2018Pardon me, Lord, I have never been a good speaker. I am slow of speech and tongue.' He begged God to send someone else instead.\u201d",
                activityNote: null,
                keyQuestion: null,
                teacherGuidance: null,
              },
              {
                heading: "God's anger \u2014 and God's provision",
                minutes: "2\u20133 min",
                teacherTalk: "\u201cGod's anger burned against Moses for still trying to get out of the job \u2014 but even angry, God didn't give up on him.\u201d Explain that God reminded Moses his brother Aaron was already on his way to meet him, and that Aaron could speak on Moses's behalf while Moses told him what to say.",
                activityNote: null,
                keyQuestion: "What does it show us about God that he had already arranged for Aaron to help Moses, even before Moses asked, and even while God was frustrated with him?",
                teacherGuidance: "Guide toward: God knows our weaknesses ahead of time and provides exactly what we need to obey him. His patience and his provision go together \u2014 he doesn't demand that we do everything completely alone, even when he's disappointed in our reluctance.",
              },
              {
                heading: "Whole-week recap relay",
                minutes: "2\u20133 min",
                teacherTalk: "In table groups, have students retell the whole week's story in order: the burning bush and holy ground, God's rescue plan and the name \u2018I AM', Moses's doubts and the three signs, and God providing Aaron.",
                activityNote: "Use the built-in whole-week recap relay activity block.",
                keyQuestion: null,
                teacherGuidance: null,
              },
              {
                heading: "Looking back over the week",
                minutes: "2\u20133 min",
                teacherTalk: "Invite students to reflect on how Moses changed across the whole week's story, from hiding by the bush to finally being ready to go.",
                activityNote: null,
                keyQuestion: "Moses started out full of excuses and doubts. By the end, was he ready to go? What changed?",
                teacherGuidance: "Guide toward: Moses wasn't naturally brave or qualified, but God's patient reassurance, the signs, and Aaron's help gave him what he needed to obey \u2014 even while he was probably still nervous.",
              },
              {
                heading: "Memory verse, from memory",
                minutes: "2 min",
                teacherTalk: "Close the week by inviting the class to say the memory verse together entirely from memory, without looking at the screen.",
                activityNote: "Use the built-in verse block, then the say-it-together activity that follows it in the app.",
                keyQuestion: null,
                teacherGuidance: null,
              },
            ],
            whereToNext: "Week 23 (Lesson 3) picks up with Moses and Aaron confronting Pharaoh, and the start of the plagues on Egypt.",
          },
        },
      ],
    },
});
